# Generated by Django 4.2.6 on 2023-11-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_audiofile_main_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
