# Generated by Django 4.2.6 on 2023-11-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_audiofile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
