# Generated by Django 4.2.6 on 2023-11-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_audiofile_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio_File_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('main_points', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='audiofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='audiofile',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='audiofile',
            name='main_points',
        ),
    ]
